POST http://localhost:3000/api/reservas
Content-Type: application/json

{
    "nombre": "belen",
    "apellido": "Raba",
    "email": "nestor@gmail.com",
    "numeroPersonas": 1,
    "hora": "14:30",
    "fecha": "2024-12-10"
}

###

GET http://localhost:3000/api/reservas
